export default {
  menu: '<i class="fa fa-bars"/>',
  filter: '<i class="fa fa-filter"/>',
  columns: '<i class="fa fa-handshake-o"/>',
  sortUnSort: '<i class="fa fa-arrows-v"/>',
  sortAscending: '<i class="fa fa-long-arrow-down"/>',
  sortDescending: '<i class="fa fa-long-arrow-up"/>',
  groupExpanded: '<i class="fa fa-minus-square-o"/>',
  groupContracted: '<i class="fa fa-plus-square-o"/>',
  columnMovePin: '<i class="fa fa-hand-grab-o"/>',
  columnMoveAdd: '<i class="fa fa-plus-square-o"/>',
  columnMoveHide: '<i class="fa fa-remove"/>',
  columnMoveMove: '<i class="fa fa-arrows"/>',
  columnMoveLeft: '<i class="fa fa-arrow-left"/>',
  columnMoveRight: '<i class="fa fa-arrow-right"/>',
  columnMoveGroup: '<i class="fa fa-group"/>',
  rowGroupPanel: '<i class="fa fa-bank"/>',
  pivotPanel: '<i class="fa fa-magic"/>',
  valuePanel: '<i class="fa fa-magnet"/>',
  menuPin: 'P', // just showing letters, no graphic
  menuValue: 'V',
  menuAddRowGroup: 'A',
  menuRemoveRowGroup: 'R',
  clipboardCopy: '>>',
  clipboardPaste: '>>',
  checkboxChecked: '<i class="fa fa-check-square-o"/>',
  checkboxUnchecked: '<i class="fa fa-square-o"/>',
  checkboxIndeterminate: '<i class="fa fa-minus-square-o"/>'
}
